remote_theme: CaptainIRS/hacker-plus-theme

title: Dian Z
author: Dian Z
description:
disqus_forum_shortname:
google_site_verification_content: # The 'content' tag for site verification
google_analytics: UA-209172679-1

# Usernames and badges

github_username: DianZzzz
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin:
twitch:
youtube:
twitter: sassypandacap
facebook:
instagram: d.zhao
reddit:
pinterest:
telegram:
steam:
email:
discord: fantasticbaby#9636

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
   - jekyll-feed
   - jekyll-paginate
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-maps
paginate: 5
paginate_path: "/:num/"
collections:
   pages:
      output: true
      permalink: /:name
   finance:
      output: true
   tech:
      output: true
   code:
      output: true
   random:
      output: true
   datascience:
      output: true
   hobbies:
      output: true
maps:
    google:
      api_key: <YOUR_KEY>
